name: update

on:
  schedule:
    - cron: '1 0 * * *'
    
  workflow_dispatch:
  
jobs:
  update:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Do the thing
        run: ./do_the_thing.sh
